### PR TITLE
NBE auto subscription message alert banner

### PR DESCRIPTION
**Pull request by sbinlondon**
This is a new messaging component for our Envoy journey - NBE auto subscription - which automatically signs up B2B triallists to 3 newsletters, unless they opt out by acting on this alert banner.

It's fairly simple, just the neutral Origami alert banner in the top slot, so I think this is everything: create partial and add it to the manifest.

### CODE REVIEW

**Comment by sbinlondon** [comment]
@liamkeaton @CourtneyLO Is it possible to start getting a review on this please?

**Comment by sjparkinson** [comment]
Could we get some before/after screenshots? I've not got much context of this change.

**Comment by sjparkinson** [comment]
News by Email (NBE), aka newsletters https://www.ft.com/newsletters.

Related pull request is https://github.com/Financial-Times/next-ammit-api/pull/562.

**Comment by sbinlondon** [comment]
I'm not sure what you mean by before/after screenshots?

I'm adding a message to the top slot - there wasn't one like this before, so there's no before.

Here's a screenshot of what the message looks like.

Screenshot 2019-07-31 at 12 00 44

**Comment by sbinlondon** [comment]
Thanks @CourtneyLO - can someone merge the branch? I am not authorised.

**Pull request merged**
