### PR TITLE
Use o-cookie-message instead of custom cookie message.

### PR DESCRIPTION
**Pull request by notlee**
I believe they’re separate because o-cookie-message was built
after the n-messaging-client version to support more products,
but the original n-messaging-client version was never swapped for
o-cookie-message.

- This accounts for accessibility improvements made to
n-messaging-client since the release of o-cookie-message.
I'll update o-cookie-message accordingly so more teams/products
benefit.
https://github.com/Financial-Times/n-messaging-client/pull/176
- `data-o-banner-action` and other `data-o-banner` data attributes
remain on o-cookie-message markup as I do not know if they may be
relied on somewhere, I'm thinking specifically about analytics,
and will leave those for a Customer Products team member to
remove in the future if they are not required.
- This removes CSS for variations: a, b, and c. They have not
been in use for > 2 years. They are still registered in
`manifest.js` however since I do not know if removing
them would constitute a major release - I don't want to give the 
accounts team more work than I need to!
https://github.com/Financial-Times/next-ammit-api/pull/423
https://github.com/Financial-Times/next-ammit-api/pull/434

fixes: https://github.com/Financial-Times/n-messaging-client/issues/133

before/after (desktop):
Screen Shot 2020-11-25 at 14 14 26
Screen Shot 2020-11-25 at 14 13 24

before/after (mobile):
Screen Shot 2020-11-25 at 14 14 47
Screen Shot 2020-11-25 at 14 15 15

### CODE REVIEW

**Review by thurstontye — APPROVED** [review]
LGTM 👍

**Comment by notlee** [comment]
Thanks for the review @thurstontye! would you mind merging and releasing this for me? Unfortunately I don't have permission as I'm not a member of Customer Products :(

**Comment by thurstontye** [comment]
@notlee happy to but would you mind dealing with the update first.

**Comment by notlee** [comment]
@thurstontye did you mean to update against the master branch? I've merged that in and the tests are passing, should be good to go :)

**Pull request merged**
